[build]
  command = "npm install && npm run build && cd front && npm install && npm run build"
  publish = "front/dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/health"
  to = "/.netlify/functions/api"
  status = 200

[[redirects]]
  from = "/api/courses"
  to = "/.netlify/functions/api"
  status = 200

[[redirects]]
  from = "/api/sections"
  to = "/.netlify/functions/api"
  status = 200

[[redirects]]
  from = "/api/faculties"
  to = "/.netlify/functions/api"
  status = 200

[[redirects]]
  from = "/api/recommendations"
  to = "/.netlify/functions/api"
  status = 200

[[redirects]]
  from = "/api/admin"
  to = "/.netlify/functions/api"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
